from currency_converter import CurrencyConverter

currencyConverter = CurrencyConverter()

currency_symbols = {
    "USD": "$",
    "CAD": "CA$",
    "EUR": "€",
    "GBP": "£",
    "JPY": "¥",
    "AUD": "A$",
    "CHF": "CHF",
    "CNY": "CN¥",
    "SEK": "kr",
    "NZD": "NZ$",
    "KRW": "₩",
    "SGD": "S$",
    "NOK": "kr",
    "MXN": "Mex$",
    "INR": "₹",
    "RUB": "₽",
    "BRL": "R$",
    "ZAR": "R",
    "TRY": "₺",
    "HKD": "HK$",
    "IDR": "Rp",
    "PLN": "zł",
    "THB": "฿",
    "DKK": "kr",
    "MYR": "RM",
    "HUF": "Ft",
    "CZK": "Kč",
    "ILS": "₪",
    "PHP": "₱",
    "AED": "AED",
    "ARS": "ARS",
    "CLP": "CLP$",
    "COP": "COL$",
    "EGP": "EGP",
    "PEN": "S/.",
    "QAR": "QR",
    "SAR": "SR",
    "TWD": "NT$",
    "UAH": "₴",
    "VND": "₫"
}

currencies = []
for k, v in currency_symbols.items():
    currencies.append(k)

valid_general_locations = [
    'United States',
    'Canada',
    'United Kingdom',
    'European Union',  # Grouping EU countries together
    'Australia',
    'New Zealand',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Netherlands',
    'Switzerland',
    'Sweden',
    'Norway',
    'Denmark',
    'Finland',
    'Belgium',
    'Austria',
    'Ireland',
    'Portugal',
    'Greece',
    'Poland',
    'Czech Republic',
    'Hungary',
    'Turkey',
    'Russia',
    'Japan',
    'South Korea',
    'China',
    'India',
    'Brazil',
    'Mexico',
    'Argentina',
    'South Africa',
    'Egypt',
    'Saudi Arabia',
    'United Arab Emirates',
    'Israel',
    'Singapore',
    'Malaysia',
    'Thailand',
    'Indonesia',
    'Philippines',
    'Vietnam',
    'Taiwan',
    'Hong Kong',
    'Macau',
    'Puerto Rico',
    'Chile',
    'Colombia',
    'Peru',
    'Venezuela',
    'Ecuador',
    'Uruguay',
    'Costa Rica',
    'Panama',
    'Cuba',
    'Jamaica',
    'Trinidad and Tobago',
    'Bahamas',
    'Barbados',
    'Dominican Republic',
    'Haiti',
    'Nicaragua',
    'Honduras',
    'El Salvador',
    'Guatemala',
    'Belize',
    'Guyana',
    'Suriname',
    'Paraguay',
    'Bolivia',
    'Guyane',
    'Martinique',
    'Guadeloupe',
    'Saint Martin',
    'Saint Barthélemy',
    'Saint Pierre and Miquelon',
    'Réunion',
    'Mayotte',
    'French Polynesia',
    'New Caledonia',
    'Wallis and Futuna',
    'French Southern and Antarctic Lands',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Falkland Islands',
    'Cook Islands',
    'Norfolk Island',
    'Tokelau',
    'Niue',
    'Pitcairn Islands',
    'Antarctica',
    'Western Sahara',
    'Kosovo',
    'Palestine',
    'Northern Cyprus',
    'Abkhazia',
    'South Ossetia',
    'Transnistria',
    'Somaliland',
    'Republic of Artsakh',
    'Sahrawi Arab Democratic Republic',
    'Nagorno-Karabakh Republic',
    'Turkish Republic of Northern Cyprus',
    'Cook Islands',
    'Niue',
    'Aruba',
    'Curacao',
    'Sint Maarten',
    'Bonaire',
    'Saba',
    'Sint Eustatius',
    'Greenland',
    'Faroe Islands',
    'Åland Islands',
    'British Overseas Territories',  # Grouping UK territories together
    'American Samoa',
    'Guam',
    'Northern Mariana Islands',
    'Puerto Rico',
    'United States Minor Outlying Islands',
    'Wake Island',
    'Midway Atoll',
    'Navassa Island',
    'Johnston Atoll',
    'Kingman Reef',
    'Jarvis Island',
    'Baker Island',
    'Howland Island',
    'Palmyra Atoll',
]

valid_general_locations.sort()